//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int id { get; set; }
        public System.DateTime fechaIng { get; set; }
        public System.DateTime fechaRet { get; set; }
        public int costo { get; set; }
        public int rut { get; set; }
        public int habitacion { get; set; }
    
        public virtual Habitacion Habitacion1 { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
