//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Reservas = new HashSet<Reserva>();
        }
    
        public int rut { get; set; }
        public string pwd { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual ICollection<Reserva> Reservas { get; set; }
    }
}
